In [336]:
import numpy as np
%config IPCompleter.greedy=True

# Numpy Scalar operation

In [174]:
a=np.array([4,5,6,7,8])
a

array([4, 5, 6, 7, 8])

In [175]:
a+1


array([5, 6, 7, 8, 9])

In [176]:
a*3

array([12, 15, 18, 21, 24])

In [177]:
a**2

array([16, 25, 36, 49, 64])

In [178]:
b=np.ones(5)
b


array([1., 1., 1., 1., 1.])

In [179]:
b-a

array([-3., -4., -5., -6., -7.])

In [180]:
a+b


array([5., 6., 7., 8., 9.])

In [181]:
a**2+b

array([17., 26., 37., 50., 65.])

In [182]:
a=np.diag([3,4,5,6])
a

array([[3, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 6]])

In [183]:
a*a

array([[ 9,  0,  0,  0],
       [ 0, 16,  0,  0],
       [ 0,  0, 25,  0],
       [ 0,  0,  0, 36]])

In [184]:
a.dot(a)

array([[ 9,  0,  0,  0],
       [ 0, 16,  0,  0],
       [ 0,  0, 25,  0],
       [ 0,  0,  0, 36]])

# Array Compare

In [185]:
x=np.array([1,4,8,12])
y=np.array([2,5,7,12])
x==y

array([False, False, False,  True])

In [186]:
x>y

array([False, False,  True, False])

In [187]:
x<y

array([ True,  True, False, False])

In [188]:
x!=y

array([ True,  True,  True, False])

In [189]:
x=np.array([1,4,8,12])
y=np.array([2,5,7,12])
z=np.array([1,4,8,12])

np.array_equal(x,y)

False

In [190]:
np.array_equal(x,z)

True

# Logical Operations

In [191]:
a=np.array([1,1,0,1],dtype=bool)
b=np.array([1,0,0,1],dtype=bool)

In [192]:
np.logical_and(a,b)

array([ True, False, False,  True])

In [193]:
np.logical_or(a,b)

array([ True,  True, False,  True])

In [194]:
np.logical_not(a)

array([False, False,  True, False])

In [195]:
np.logical_xor(a,b)

array([False,  True, False, False])

# Transcendental Fucntions

In [196]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [197]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [198]:
np.log(a)

/Users/jymisra/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [199]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

# Shape Mismatch

In [200]:
a=np.arange(4)
a

array([0, 1, 2, 3])

In [201]:
b=np.array([8,9])
b

array([8, 9])

In [202]:
a+b

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

# Basic Reductions

In [203]:
a=np.array([1,2,3,4,5,6])
a.sum()

21

mat=np.array([[1,1],[2,2]])
mat

In [204]:
type(mat)

numpy.ndarray

In [205]:
mat.ndim

2

In [206]:
mat.sum()

6

In [207]:
mat.sum(axis=0)

array([3, 3])

In [208]:
mat.sum(axis=1)

array([2, 4])

# Other Reductions

In [209]:
aa=np.array([5,8,2,9,4,5,88,99,77])
aa

array([ 5,  8,  2,  9,  4,  5, 88, 99, 77])

In [210]:
aa.min()

2

In [211]:
aa.max()

99

In [212]:
aa.argmin()

2

In [213]:
aa.argmax()

7

# Logical Operators

In [214]:
np.all([True,True,True])   # If all true then TRUE

True

In [215]:
np.all([True,True,False])  #If all true then TRUE else FALSE

False

In [216]:
np.any([True,True,True]) #If anyone is TRUE then TRUE

True

In [217]:
np.all([True,True,False]) 

False

In [218]:
np.all([False,False,False]) #If anyone is TRUE then TRUE else FALSEE

False

In [219]:
#Array Comaprison
b=np.zeros(4)
b

array([0., 0., 0., 0.])

In [220]:
np.all(b==0)

True

In [221]:
np.all(b!=0)

False

In [222]:
c=np.eye(4)
c

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [223]:
np.any(c==1)

True

In [224]:
np.all(c==1)

False

In [225]:
np.any(c==0)

True

In [226]:
aa=np.array([1,2,3,2])
bb=np.array([2,2,3,2])
cc=np.array([6,4,4,5])
(aa>=bb)

array([False,  True,  True,  True])

In [227]:
bb<cc

array([ True,  True,  True,  True])

In [228]:
(aa >= bb)&(bb < cc)

array([False,  True,  True,  True])

In [229]:
((aa >= bb)&(bb < cc)).any()

True

In [230]:
((aa >= bb)&(bb < cc)).all()

False

# Statistics

In [231]:
x=np.array([2,4,6,6,8])

In [232]:
x.mean()

5.2

In [233]:
np.median(x)

6.0

In [234]:
x.std()  #Stamdrad Deviation

2.039607805437114

In [235]:
xx= np.array([[1,2,3,4],[5,6,7,8]])
xx

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [236]:
xx.mean(axis=1)

array([2.5, 6.5])

In [237]:
xx.mean(axis=0,dtype=int)

array([3, 4, 5, 6])

In [238]:
xx.mean(axis=0)

array([3., 4., 5., 6.])

In [239]:
np.median(xx,axis=-1)

array([2.5, 6.5])

# Example 

In [240]:
hare_data=np.loadtxt("populations.txt")

In [241]:
hare_data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [242]:
hare_data.size


84

In [243]:
hare_data.shape

(21, 4)

In [244]:
hare_data.ndim

2

In [245]:
population=hare_data[:,1:]
population

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [246]:
population.argmax(axis=1)   #INDEX of max element column wise

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2])

# Broadcasting

In [247]:
np.tile(np.arange(0,40,10),(3,1))

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [248]:
np.tile(np.arange(0,40,10),(3,2))

array([[ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30]])

In [263]:
a=np.tile(np.arange(0,40,10),(3,1))

In [264]:
a=a.T

In [265]:
b=np.array([0,1,2])
b

array([0, 1, 2])

# Converting 1D TO 2D

In [266]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [267]:
aa = np.arange(0,40,10)
aa.shape

(4,)

In [268]:
aa=aa[:,np.newaxis]
aa.shape

(4, 1)

In [269]:
aa

array([[ 0],
       [10],
       [20],
       [30]])

In [270]:
bb=np.array([0,1,2])
bb

array([0, 1, 2])

In [271]:
aa+bb

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

# Array Shape Manipulation

In [280]:
x = np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [282]:
x.ravel()

array([1, 2, 3, 4, 5, 6])

In [283]:
x.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [285]:
x.T.flatten()

array([1, 4, 2, 5, 3, 6])

# Reshape

In [287]:
aa = np.array([[1,2,3],[4,5,6]])
aa

array([[1, 2, 3],
       [4, 5, 6]])

In [290]:
bb=aa.ravel()
bb

array([1, 2, 3, 4, 5, 6])

In [294]:
bb=bb.reshape(2,3)

Now Change a Values in bb ,in aa also it will change as bothe refer to same memory location

In [295]:
bb[1,2]=1000

In [296]:
aa

array([[   1,    2,    3],
       [   4,    5, 1000]])

In [297]:
bb

array([[   1,    2,    3],
       [   4,    5, 1000]])

In [299]:
mdim =np.arange(4*3*2).reshape(4,3,2)
mdim

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [300]:
mdim[2,2,0]

16

In [301]:
mdim[2,1,1]

15

# Resizing

In [323]:
p = np.arange(4)
p

array([0, 1, 2, 3])

In [326]:
p=np.resize(p,(8,))
p

array([0, 1, 2, 3, 0, 1, 2, 3])

In [327]:
p=np.resize(p,(15,))
p

array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2])

In [328]:
q = np.arange(4)
q

array([0, 1, 2, 3])

In [335]:
q.resize((10,),refcheck=False)
q

array([0, 1, 2, 3, 0, 0, 0, 0, 0, 0])

# Sorting

In [345]:
aa=np.array([[4,6,2],[2,2,5]])
aa

array([[4, 6, 2],
       [2, 2, 5]])

In [349]:
bb=np.sort(aa)     # use np.sort() to return the result
bb

array([[2, 4, 6],
       [2, 2, 5]])

In [350]:
aa=np.array([[4,6,2],[2,2,5],[5,99,100]])
aa

array([[  4,   6,   2],
       [  2,   2,   5],
       [  5,  99, 100]])

In [352]:
aa.sort()#aa.sort()modifies aa 
aa

array([[  2,   4,   6],
       [  2,   2,   5],
       [  5,  99, 100]])

In [355]:
bb=np.array([[4,6,2],[2,2,5],[5,99,100]])
bb


array([[  4,   6,   2],
       [  2,   2,   5],
       [  5,  99, 100]])

In [356]:
bb.sort(axis=0)
bb

array([[  2,   2,   2],
       [  4,   6,   5],
       [  5,  99, 100]])

# Sorting with Fancy Indexing

In [357]:
arr = np.array([4,5,1,3,2])
arr

array([4, 5, 1, 3, 2])

In [358]:
j=arr.argsort() # array j contains sorted index
j

array([2, 4, 3, 0, 1])

In [359]:
arr[j]  #Displays Sorted Array

array([1, 2, 3, 4, 5])