In [120]:
import numpy as np
%config IPCompleter.greedy=True

In [2]:
arr=np.array([0,2,4,6])

In [3]:
arr

array([0, 2, 4, 6])

In [67]:
type(arr)

numpy.ndarray

In [6]:
arr.shape

(4,)

In [7]:
arr.size

4

In [25]:
arr.ndim

1

In [26]:
len(arr)

4

In [18]:
a1=np.arange(20)
print(a1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


# Memory Efficient

In [24]:
A1=range(100)  #List from 0..999
%timeit [i**2 for i in A1]

27.2 µs ± 1.89 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [23]:
A2=np.arange(1000)
%timeit A2**2

1.06 µs ± 54.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


Numpy is 200 times faster as per above examples

# Two Dimensional Arrays

In [31]:
arr2=np.array([[0,1,2],[3,4,5]])
arr2

array([[0, 1, 2],
       [3, 4, 5]])

In [32]:
arr2.size

6

In [33]:
arr2.ndim

2

In [36]:
arr2.shape

(2, 3)

In [37]:
len(arr2)  # It prints domension ,here it is 2

2

 **1D Array = Vector <br>
2D Array = Matrix <br>
3D Array = Tensor**


# Numpy Array Operations

In [38]:
aa=np.arange(10)
aa

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
ab=np.arange(1,10,2)
ab

array([1, 3, 5, 7, 9])

In [64]:
ab=np.arange(1,10,2,dtype=float)
ab

array([1., 3., 5., 7., 9.])

In [45]:
ac=np.linspace(1,10,5)
ac

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [49]:
np.ones(4)

array([1., 1., 1., 1.])

In [52]:
np.ones([4,3],dtype= int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [54]:
np.ones([4,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [57]:
np.zeros([4,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [58]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [59]:
np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [60]:
np.eye(4,dtype=int).ndim

2

In [61]:
np.eye(4,dtype=int).size

16

In [62]:
np.diag([5,6,7,8])

array([[5, 0, 0, 0],
       [0, 6, 0, 0],
       [0, 0, 7, 0],
       [0, 0, 0, 8]])

In [63]:
np.diag([5,6,7,8,9,10,11])

array([[ 5,  0,  0,  0,  0,  0,  0],
       [ 0,  6,  0,  0,  0,  0,  0],
       [ 0,  0,  7,  0,  0,  0,  0],
       [ 0,  0,  0,  8,  0,  0,  0],
       [ 0,  0,  0,  0,  9,  0,  0],
       [ 0,  0,  0,  0,  0, 10,  0],
       [ 0,  0,  0,  0,  0,  0, 11]])

# Slicing

In [68]:
ar=np.arange(1,20,4)

In [69]:
ar

array([ 1,  5,  9, 13, 17])

In [71]:
ar1=np.arange(1,15,2)
ar1

array([ 1,  3,  5,  7,  9, 11, 13])

In [73]:
ar1[4:] = 15   #Replace all values from location 4 
ar1

array([ 1,  3,  5,  7, 15, 15, 15])

In [75]:
ar2=np.arange(10)
ar2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
ar4=np.array([55,66,77,88,99,111])
ar4

array([ 55,  66,  77,  88,  99, 111])

In [88]:
ar4[2:] = ar1[1:5]
ar4

array([55, 66,  3,  5,  7, 15])

In [86]:
ar3=ar2[:5]
ar3

array([0, 1, 2, 3, 4])

# Copies and Views

In [81]:
x=np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
y = x[5:]
y

array([6, 7, 8, 9])

In [89]:
np.shares_memory(x,y)  # x and y shares same memory

True

In [92]:
y[-1]=999    #x and y both changed a shares same memory
print("y is " ,y)
print("x is" ,x)

y is  [  6   7   8 999]
x is [  1   2   3   4   5   6   7   8 999]


# Force Copy

In [93]:
aa = np.arange(6,15)
aa

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [96]:
bb=aa[5:].copy()
bb

array([11, 12, 13, 14])

In [97]:
np.shares_memory(aa,bb)  #As force copied

False

In [98]:
bb[-1]=888
print("bb is " ,bb)
print("aa is" ,aa)

bb is  [ 11  12  13 888]
aa is [ 6  7  8  9 10 11 12 13 14]


# Fancy Indexing

In [104]:
xx = np.random.randint(1,20,15)
xx

array([ 6,  7, 10,  2,  8, 11, 16, 19, 11, 10,  6, 13, 15,  1, 15])

In [105]:
mask =(xx %2 ==0) #Collect Even Numbers 

In [106]:
extract =xx[mask]   #masks createe copies and not views
extract

array([ 6, 10,  2,  8, 16, 10,  6])

In [107]:
xx[mask]= -5  #All evennumber to -5
xx

array([-5,  7, -5, -5, -5, 11, -5, 19, 11, -5, -5, 13, 15,  1, 15])

In [109]:
yy = np.arange(0,20,2)
yy

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [114]:
yy[[2,5,8]]

array([ 4, 10, 16])

In [115]:
yy

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [116]:
yy[[2,5,8]]= 9999

In [117]:
yy

array([   0,    2, 9999,    6,    8, 9999,   12,   14, 9999,   18])

In [119]:
yy[[0,5,1,5,1,4,4]] #Repeated index values

array([   0, 9999,    2, 9999,    2,    8,    8])